### ISSUE TITLE
Office hours broken?

### ISSUE THREAD

**Issue by decentral1se** [ssbc/dev.scuttlebutt.nz#26]
![image](https://user-images.githubusercontent.com/1991377/204918056-6da71e6c-b7be-4d13-ad33-a3085dffbb10.png)

**Comment by mycognosist** [comment]
This was working yesterday when I happened to visit the site. The feature was introduced in https://github.com/ssbc/dev.scuttlebutt.nz/pull/20

CC: @mplorentz

**Comment by mplorentz** [comment]
Ah, thanks for reporting this. I believe I was the only one posting events on this calendar, and I stopped doing my office hours a few months ago. I think the calendar can be removed. It's been a task on my back burner but I will try to get a PR submitted this week.

**Comment by mplorentz** [comment]
Thanks @decentral1se! Personal life has been busy, sorry I didn't come through.
