### ISSUE TITLE
Naming and styling

### ISSUE THREAD

**Issue by mycognosist** [ssbc/dev.scuttlebutt.nz#7]
Hey @arj03 and @mixmix ,

It feels like this project is coming together nicely. I've recently added syntax highlighting for the Go and Rust code examples, and yesterday I read through everything and tidied up some spelling and grammar mistakes.

Do youse have any idea what you'd like to name the site?

mix has previously conceptualised this as "a map of where all the pieces are and how they fit together". So maybe Scuttlebutt Developer Map, or Scuttlebutt Tech Map, or maybe just Scuttlebutt Developer Documentation?

I can add the name to the `index.html` once decided up. I'm also keen on customising the homepage sidebar so it shows links for the various implementations - just so they're easier to spot at-a-glance. The rest of it all feels pretty good to me.

Are there any other changes / additions / updates you'd like to see?

**Comment by mixmix** [comment]
You know the site is live already right?

I think go for it with styling and sidebar changes

**Comment by mycognosist** [comment]
Yup, I know it's live.

Any preference on naming?

**Comment by arj03** [comment]
Maybe Scuttlebutt Treasure Map for Developers :-)
